# Generated by Django 5.2.5 on 2025-09-01 09:27

from django.db import migrations, models
import django.core.validators
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        # Rename student_id to roll_number
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='roll_number',
        ),
        
        # Add new fields
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g., 2023-2024', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='quota',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('EWS', 'Economically Weaker Section'), ('PHYSICALLY_CHALLENGED', 'Physically Challenged'), ('SPORTS', 'Sports Quota'), ('NRI', 'NRI Quota')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(blank=True, help_text='Academic or admission rank', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhar number', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('SIKH', 'Sikh'), ('BUDDHIST', 'Buddhist'), ('JAIN', 'Jain'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subcaste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Father Mobile'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mother Mobile'),
        ),
        
        # Rename phone_number to student_mobile
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='student_mobile',
        ),
        
        # Update country default
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        
        # Add custom field models
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('select', 'Select (Dropdown)'), ('multiselect', 'Multi-Select'), ('boolean', 'Yes/No'), ('textarea', 'Long Text'), ('file', 'File Upload'), ('url', 'URL')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, help_text='For select/multiselect fields, provide options as JSON array', null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=200, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='student_custom_files/')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_values', to='students.customfield')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Custom Field Value',
                'verbose_name_plural': 'Student Custom Field Values',
                'unique_together': {('student', 'custom_field')},
            },
        ),
    ]
