# Generated by Django 5.1.4 on 2025-09-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_perf_indexes'),
        ('students', '0005_student_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Student's department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.department'),
        ),
    ]
