# Generated by Django 5.1.4 on 2025-09-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_perf_indexes'),
        ('students', '0006_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='studentenrollmenthistory',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_program',
            field=models.ForeignKey(blank=True, help_text="Student's academic program (B.Tech, MBA, MCA, etc.)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.academicprogram'),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10')], default='1', help_text='Current semester', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], default='1', help_text='Current year of study (1st, 2nd, 3rd, 4th year)', max_length=1),
        ),
        migrations.AddField(
            model_name='studentenrollmenthistory',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='studentenrollmenthistory',
            name='year_of_study',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], default='1', max_length=1),
        ),
    ]
