# Generated by Django 5.1.4 on 2025-09-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmentprogram_department'),
        ('students', '0008_partial_uniques_and_perf_indexes'),
    ]

    operations = [
        # Drop and recreate the FK column to avoid bigint->uuid casting
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Student's department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='departments.department'),
        ),
    ]
