version: '3.8'

services:
  # Load Balancer
  nginx:
    image: nginx:alpine
    container_name: campushub_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - django1
      - django2
      - django3
      - django4
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Application Instances
  django1:
    build: .
    container_name: campushub_django1
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GUNICORN_WORKERS=4
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - redis
      - postgres
    command: gunicorn --config gunicorn.conf.py campshub360.wsgi:application

  django2:
    build: .
    container_name: campushub_django2
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - GUNICORN_WORKERS=4
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - redis
      - postgres
    command: gunicorn --config gunicorn.conf.py campshub360.wsgi:application

  django3:
    build: .
    container_name: campushub_django3
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      - PORT=8000
      - GUNICORN_WORKERS=4
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - redis
      - postgres
    command: gunicorn --config gunicorn.conf.py campshub360.wsgi:application

  django4:
    build: .
    container_name: campushub_django4
    restart: unless-stopped
    ports:
      - "8003:8000"
    environment:
      - PORT=8000
      - GUNICORN_WORKERS=4
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - redis
      - postgres
    command: gunicorn --config gunicorn.conf.py campshub360.wsgi:application

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: campushub_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: campushub_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=campushub360
      - POSTGRES_USER=campushub
      - POSTGRES_PASSWORD=Campushub123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U campushub -d campushub360"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Monitoring
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: campushub_redis_commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
