# Generated by Django 5.2.5 on 2025-09-01 12:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('CHAR', 'Text'), ('TEXT', 'Long Text'), ('INTEGER', 'Number'), ('DECIMAL', 'Decimal Number'), ('DATE', 'Date'), ('DATETIME', 'Date & Time'), ('BOOLEAN', 'Yes/No'), ('EMAIL', 'Email'), ('URL', 'URL'), ('PHONE', 'Phone Number'), ('CHOICE', 'Choice Field')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated choices for choice fields', null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Faculty'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='apaar_faculty_id',
            field=models.CharField(default='', help_text='APAAR Faculty ID', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='area_of_specialization',
            field=models.CharField(blank=True, help_text='Area of Specialization', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='contractual_full_time_part_time',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], help_text='If contractual mention Full time or Part time', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='currently_associated',
            field=models.BooleanField(default=True, help_text='Currently Associated (Y/N)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_designated_as_professor',
            field=models.DateField(blank=True, help_text='Date designated as Professor/Associate Professor', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_of_joining_institution',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of Joining in this Institution'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation_at_joining',
            field=models.CharField(default='', help_text='Designation at Time of Joining in this Institution', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='experience_in_current_institute',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Experience in years in current institute', max_digits=4),
        ),
        migrations.AddField(
            model_name='faculty',
            name='highest_degree',
            field=models.CharField(default='', help_text='Highest Degree', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='', help_text='Name of the Faculty', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='nature_of_association',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('CONTRACT', 'Contract'), ('AD_HOC', 'Ad hoc')], default='REGULAR', help_text='Nature of Association', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pan_no',
            field=models.CharField(blank=True, help_text='PAN Number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='present_designation',
            field=models.CharField(default='', help_text='Present Designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='address_line_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_leaving',
            field=models.DateField(blank=True, help_text='Date of Leaving if any', null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('COMPUTER_SCIENCE', 'Computer Science'), ('MATHEMATICS', 'Mathematics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('ENGLISH', 'English'), ('HISTORY', 'History'), ('GEOGRAPHY', 'Geography'), ('ECONOMICS', 'Economics'), ('COMMERCE', 'Commerce'), ('PHYSICAL_EDUCATION', 'Physical Education'), ('ARTS', 'Arts'), ('MUSIC', 'Music'), ('ADMINISTRATION', 'Administration'), ('OTHER', 'Other')], default='OTHER', max_length=25),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('LECTURER', 'Lecturer'), ('INSTRUCTOR', 'Instructor'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('DEAN', 'Dean'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal')], default='LECTURER', max_length=25),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emergency_contact_relationship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employee_id',
            field=models.CharField(default='', help_text='Unique employee identifier', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('VISITING', 'Visiting'), ('ADJUNCT', 'Adjunct')], default='FULL_TIME', max_length=15),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='highest_qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.CharField(blank=True, help_text='University', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultydocument',
            name='document_type',
            field=models.CharField(choices=[('RESUME', 'Resume/CV'), ('DEGREE_CERTIFICATE', 'Degree Certificate'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate'), ('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('PHOTO', 'Photograph'), ('PAN_CARD', 'PAN Card'), ('AADHAR_CARD', 'Aadhar Card'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.customfield')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='faculty.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'custom_field')},
            },
        ),
    ]
