# Generated by Django 5.2.5 on 2025-09-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicprogram_alter_courseenrollment_options_and_more'),
        ('faculty', '0002_customfield_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department_ref',
            field=models.ForeignKey(blank=True, help_text='Department reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='academics.department'),
        ),
    ]
