# Generated by Django 5.1.4 on 2025-09-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmentprogram_department'),
        ('faculty', '0003_faculty_department_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='department_ref',
        ),
        migrations.AddField(
            model_name='faculty',
            name='department_ref',
            field=models.ForeignKey(blank=True, help_text='Department reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='departments.department'),
        ),
    ]
