# Generated by Django 5.1.4 on 2025-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_perf_indexes'),
        ('students', '0009_alter_student_department'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'status'], name='fees_studen_student_6cb40a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['due_date', 'status'], name='fees_studen_due_dat_021b9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('amount_due__gte', 0)), name='student_fee_amount_due_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='student_fee_amount_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('late_fee_amount__gte', 0)), name='student_fee_late_fee_nonnegative'),
        ),
    ]
