# Generated by Django 5.2.5 on 2025-09-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicprogram_alter_courseenrollment_options_and_more'),
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_role', models.CharField(max_length=255)),
                ('package_annual_ctc', models.DecimalField(decimal_places=2, help_text='Annual CTC', max_digits=12)),
                ('joining_location', models.CharField(blank=True, max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='placements.application')),
            ],
            options={
                'ordering': ['-offered_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('drive_type', models.CharField(choices=[('CAMPUS', 'On Campus'), ('POOL', 'Pool Campus'), ('VIRTUAL', 'Virtual')], default='CAMPUS', max_length=10)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_backlogs_allowed', models.PositiveIntegerField(default=0)),
                ('batch_year', models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placements.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drives', to=settings.AUTH_USER_MODEL)),
                ('eligible_departments', models.ManyToManyField(blank=True, related_name='placement_drives', to='academics.department')),
                ('eligible_programs', models.ManyToManyField(blank=True, related_name='placement_drives', to='academics.academicprogram')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('round_type', models.CharField(choices=[('APTITUDE', 'Aptitude Test'), ('TECH_TEST', 'Technical Test'), ('GD', 'Group Discussion'), ('TECH_INTERVIEW', 'Technical Interview'), ('HR_INTERVIEW', 'HR Interview'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='placements.placementdrive')),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='placements.placementdrive'),
        ),
    ]
