# Generated by Django 5.1.4 on 2025-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmentprogram_department'),
        ('placements', '0002_offer_placementdrive_interviewround_and_more'),
    ]

    operations = [
        # Recreate M2M to avoid bigint->uuid cast on the through table
        migrations.RemoveField(
            model_name='placementdrive',
            name='eligible_departments',
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='eligible_departments',
            field=models.ManyToManyField(blank=True, related_name='placement_drives', to='departments.department'),
        ),
    ]
