# Generated by Django 5.2.5 on 2025-09-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_auditlog ALTER COLUMN user_agent DROP NOT NULL;",
            reverse_sql="ALTER TABLE accounts_auditlog ALTER COLUMN user_agent SET NOT NULL;"
        ),
    ]
