# Generated by Django 5.1.4 on 2025-09-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession_geo_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authidentifier',
            new_name='accounts_au_user_id_93c765_idx',
            old_name='accounts_aut_user_id__7c8bd2_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordreset',
            new_name='accounts_pa_user_id_dbf915_idx',
            old_name='accounts_pas_user_id__27a6a1_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='accounts_us_user_id_5a6a2f_idx',
            old_name='accounts_use_user_re_e2b3c6_idx',
        ),
    ]
