# Generated by Django 5.1.4 on 2025-09-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_index_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examschedule',
            new_name='idx_exam_sched_sc_date',
            old_name='idx_examschedule_session_course_date',
        ),
        migrations.RenameIndex(
            model_name='examschedule',
            new_name='idx_exam_sched_date',
            old_name='idx_examschedule_date',
        ),
    ]
