# Generated by Django 5.2.5 on 2025-09-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicprogram_alter_courseenrollment_options_and_more'),
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorships', to='academics.department'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='grade_level',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='section',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
