# Generated by Django 5.1.4 on 2025-09-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmentprogram_department'),
        ('mentoring', '0002_mentorship_academic_year_mentorship_department_ref_and_more'),
    ]

    operations = [
        # Drop and recreate to avoid bigint->uuid cast on FK
        migrations.RemoveField(
            model_name='mentorship',
            name='department_ref',
        ),
        migrations.AddField(
            model_name='mentorship',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorships', to='departments.department'),
        ),
    ]
