# Generated by Django 5.1.4 on 2025-09-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_perf_indexes'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g., 2024-2025)', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to_course_sections',
            field=models.ManyToManyField(blank=True, help_text='Course sections this assignment is assigned to', related_name='assignments', to='academics.coursesection'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this assignment is assigned to', related_name='assignments', to='academics.department'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester (e.g., Fall, Spring)', max_length=20, null=True),
        ),
    ]
