# Generated by Django 5.1.4 on 2025-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_academic_year_and_more'),
        ('departments', '0003_alter_departmentprogram_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_to_departments',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this assignment is assigned to', related_name='assignments', to='departments.department'),
        ),
    ]
