# Generated by Django 5.2.5 on 2025-09-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicprogram_alter_courseenrollment_options_and_more'),
        ('grads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='academics.department'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='academics.academicprogram'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='letter',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('letter', 'department', 'program')},
        ),
    ]
