# Generated by Django 5.1.4 on 2025-09-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmentprogram_department'),
        ('grads', '0002_gradescale_department_gradescale_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradescale',
            name='department',
        ),
        migrations.AddField(
            model_name='gradescale',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='departments.department'),
        ),
    ]
