# Generated by Django 5.1.4 on 2025-09-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmentprogram_department'),
        ('enrollment', '0003_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignment',
            name='department',
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='departments.department'),
        ),
        migrations.RemoveField(
            model_name='enrollmentrule',
            name='department',
        ),
        migrations.AddField(
            model_name='enrollmentrule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_rules', to='departments.department'),
        ),
    ]
