# Generated by Django 5.1.4 on 2025-09-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_code_35a421_idx',
            old_name='departments_code_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_short_n_f97840_idx',
            old_name='departments_short_name_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_departm_d1db1a_idx',
            old_name='departments_department_type_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_status_b12c1d_idx',
            old_name='departments_status_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_is_acti_51d68f_idx',
            old_name='departments_is_active_idx',
        ),
        migrations.AlterField(
            model_name='department',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Address line 1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
