# Generated by Django 5.1.4 on 2025-09-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_departments_code_idx_departments_code_35a421_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_programs', to='departments.department'),
        ),
    ]
