# Generated by Django 5.2.5 on 2025-09-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0002_customfield_alter_faculty_options_and_more'),
        ('students', '0004_studentimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name (e.g., Bachelor of Computer Science)', max_length=200)),
                ('code', models.CharField(help_text='Program code (e.g., BCS)', max_length=20, unique=True)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'Doctorate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate')], default='UG', max_length=20)),
                ('duration_years', models.PositiveIntegerField(default=4, help_text='Program duration in years')),
                ('total_credits', models.PositiveIntegerField(help_text='Total credits required for graduation')),
                ('description', models.TextField(blank=True, help_text='Program description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Program',
                'verbose_name_plural': 'Academic Programs',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ['-enrollment_date', 'course_section__course__code'], 'verbose_name': 'Course Enrollment', 'verbose_name_plural': 'Course Enrollments'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('AUDIT', 'Audit'), ('CREDIT_TRANSFER', 'Credit Transfer'), ('REPEAT', 'Repeat Course')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of students per section'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('WAITLISTED', 'Waitlisted'), ('PENDING', 'Pending Approval')], default='ENROLLED', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(help_text='Programs this course belongs to', related_name='courses', to='academics.academicprogram'),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(help_text='Section number (e.g., A, B, 01, 02)', max_length=10)),
                ('section_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Laboratory'), ('TUTORIAL', 'Tutorial'), ('SEMINAR', 'Seminar'), ('WORKSHOP', 'Workshop')], default='LECTURE', max_length=20)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-2025)', max_length=9)),
                ('semester', models.CharField(help_text='Semester (e.g., Fall, Spring)', max_length=20)),
                ('max_students', models.PositiveIntegerField(help_text='Maximum students for this section')),
                ('current_enrollment', models.PositiveIntegerField(default=0, help_text='Current number of enrolled students')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'ordering': ['course__code', 'section_number', 'academic_year', 'semester'],
                'unique_together': {('course', 'section_number', 'academic_year', 'semester')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.coursesection'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.coursesection'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course_section')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('course_section', 'day_of_week', 'start_time')},
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Department code (e.g., CS, ME)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
    ]
