# Generated by Django 5.1.4 on 2025-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicprogram_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogram',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_default='ACTIVE', default='ACTIVE', max_length=20),
        ),
    ]
