# Generated by Django 5.1.4 on 2025-09-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_perf_indexes'),
        ('academics', '000X_consolidate_department_fk'),
    ]

    operations = [
    ]
