# Generated by Django 5.1.4 on 2025-09-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_indexes_and_constraints'),
        ('assignments', '0003_alter_assignment_assigned_to_departments'),
        ('departments', '0003_alter_departmentprogram_department'),
        ('enrollment', '0004_alter_courseassignment_department_and_more'),
        ('faculty', '0004_alter_faculty_department_ref'),
        ('feedback', '0002_alter_feedback_department'),
        ('grads', '0003_alter_gradescale_department'),
        ('mentoring', '0003_alter_mentorship_department_ref'),
        ('placements', '0003_alter_placementdrive_eligible_departments'),
        ('students', '0009_alter_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='academicprogram',
            name='department',
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_programs', to='departments.department'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student', 'status'], name='academics_c_student_ed6491_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course_section', 'status'], name='academics_c_course__5e1d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['faculty', 'academic_year', 'semester'], name='academics_c_faculty_f36357_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['is_active'], name='academics_c_is_acti_5d626e_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.CheckConstraint(condition=models.Q(('current_enrollment__gte', 0)), name='course_section_current_enrollment_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.CheckConstraint(condition=models.Q(('current_enrollment__lte', models.F('max_students'))), name='course_section_enrollment_not_exceed_capacity'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
